# Generated by Django 4.2.1 on 2023-05-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "category",
                "verbose_name_plural": "categorie",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_access",
            field=models.BooleanField(default=True),
        ),
    ]
